sudo: true
language: python

python:
  - 3.6

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:mc3man/trusty-media; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg; fi
  - ffmpeg -version || true
  # - export GOPATH=$PWD/go-get-youtube
  # - go get github.com/knadh/go-get-youtube
  # - mv mv_files.sh go-get-youtube/bin
  # - cd go-get-youtube/bin
  # - go get -v golang.org/x/lint/golint

script:
  # Add more links later and commet out
  # 05-20-2019
  # Test Video
  # - go get github.com/kkdai/youtube/youtubedr
  # - youtubedr https://www.youtube.com/watch?v=ROQj_ZVZgfg
  - sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
  - sudo chmod a+rx /usr/local/bin/youtube-dl
  # - youtube-dl https://www.youtube.com/watch?v=ROQj_ZVZgfg --format mp4
  # 6/10/2019
  - youtube-dl https://www.youtube.com/watch?v=-3qyTaLe5BE --format mp4
  - youtube-dl https://www.youtube.com/watch?v=ZLYYRqU_iqE --format mp4
  - youtube-dl https://www.youtube.com/watch?v=FITSPSA8gQs --format mp4
  - youtube-dl https://www.youtube.com/watch?v=fZPgnFHeG3M --format mp4
  - youtube-dl https://www.youtube.com/watch?v=BHhiOta0BJE --format mp4
  - youtube-dl https://www.youtube.com/watch?v=jYYgQzidjyI --format mp4
  - ls
  # - ./go-get-youtube -id=fZPgnFHeG3M -rename -mp3 || true
  # - ./go-get-youtube -id=ROQj_ZVZgfg -itag 18 -rename -mp3 || true
  # - ./go-get-youtube -id=cN_DpYBzKso -itag 18 -rename -mp3 || true
  # - ./go-get-youtube -id=fZPgnFHeG3M -itag 36 -rename -mp3 || true
  # - ./go-get-youtube -id=fZPgnFHeG3M -itag 37 -rename -mp3 || true
  # - ./go-get-youtube -id=fZPgnFHeG3M -itag 38 -rename -mp3 || true
  # - ls
  - chmod +x mv_files.sh && ./mv_files.sh || true
  - python send_vid_email.py || true

# "GCS Interoperable Access Key ID"
# "GCS Interoperable Access Secret"
# deploy:
#   provider: gcs
#   access_key_id: $ACS
#   secret_access_key: $GCS
#   bucket: cait-music
#   skip_cleanup: true
#   acl: public-read
#   local-dir: cait_music
